// Code generated by ent, DO NOT EDIT.

package leaguecertificatetype

import (
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// LeagueID applies equality check predicate on the "league_id" field. It's identical to LeagueIDEQ.
func LeagueID(v uint64) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLeagueID), v))
	})
}

// CertificateTypeID applies equality check predicate on the "certificate_type_id" field. It's identical to CertificateTypeIDEQ.
func CertificateTypeID(v uint64) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCertificateTypeID), v))
	})
}

// LeagueIDEQ applies the EQ predicate on the "league_id" field.
func LeagueIDEQ(v uint64) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLeagueID), v))
	})
}

// LeagueIDNEQ applies the NEQ predicate on the "league_id" field.
func LeagueIDNEQ(v uint64) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLeagueID), v))
	})
}

// LeagueIDIn applies the In predicate on the "league_id" field.
func LeagueIDIn(vs ...uint64) predicate.LeagueCertificateType {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldLeagueID), v...))
	})
}

// LeagueIDNotIn applies the NotIn predicate on the "league_id" field.
func LeagueIDNotIn(vs ...uint64) predicate.LeagueCertificateType {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldLeagueID), v...))
	})
}

// CertificateTypeIDEQ applies the EQ predicate on the "certificate_type_id" field.
func CertificateTypeIDEQ(v uint64) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCertificateTypeID), v))
	})
}

// CertificateTypeIDNEQ applies the NEQ predicate on the "certificate_type_id" field.
func CertificateTypeIDNEQ(v uint64) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCertificateTypeID), v))
	})
}

// CertificateTypeIDIn applies the In predicate on the "certificate_type_id" field.
func CertificateTypeIDIn(vs ...uint64) predicate.LeagueCertificateType {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCertificateTypeID), v...))
	})
}

// CertificateTypeIDNotIn applies the NotIn predicate on the "certificate_type_id" field.
func CertificateTypeIDNotIn(vs ...uint64) predicate.LeagueCertificateType {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCertificateTypeID), v...))
	})
}

// HasLeague applies the HasEdge predicate on the "league" edge.
func HasLeague() predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LeagueTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LeagueTable, LeagueColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeagueWith applies the HasEdge predicate on the "league" edge with a given conditions (other predicates).
func HasLeagueWith(preds ...predicate.League) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LeagueInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LeagueTable, LeagueColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCertificates applies the HasEdge predicate on the "certificates" edge.
func HasCertificates() predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CertificatesTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CertificatesTable, CertificatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCertificatesWith applies the HasEdge predicate on the "certificates" edge with a given conditions (other predicates).
func HasCertificatesWith(preds ...predicate.CertificateType) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CertificatesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CertificatesTable, CertificatesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LeagueCertificateType) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LeagueCertificateType) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LeagueCertificateType) predicate.LeagueCertificateType {
	return predicate.LeagueCertificateType(func(s *sql.Selector) {
		p(s.Not())
	})
}
