// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/bug/ent/league"
	"entgo.io/bug/ent/leaguecertificatetype"
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LeagueQuery is the builder for querying League entities.
type LeagueQuery struct {
	config
	limit                     *int
	offset                    *int
	unique                    *bool
	order                     []OrderFunc
	fields                    []string
	predicates                []predicate.League
	withLeagueCertificateType *LeagueCertificateTypeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LeagueQuery builder.
func (lq *LeagueQuery) Where(ps ...predicate.League) *LeagueQuery {
	lq.predicates = append(lq.predicates, ps...)
	return lq
}

// Limit adds a limit step to the query.
func (lq *LeagueQuery) Limit(limit int) *LeagueQuery {
	lq.limit = &limit
	return lq
}

// Offset adds an offset step to the query.
func (lq *LeagueQuery) Offset(offset int) *LeagueQuery {
	lq.offset = &offset
	return lq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lq *LeagueQuery) Unique(unique bool) *LeagueQuery {
	lq.unique = &unique
	return lq
}

// Order adds an order step to the query.
func (lq *LeagueQuery) Order(o ...OrderFunc) *LeagueQuery {
	lq.order = append(lq.order, o...)
	return lq
}

// QueryLeagueCertificateType chains the current query on the "league_certificate_type" edge.
func (lq *LeagueQuery) QueryLeagueCertificateType() *LeagueCertificateTypeQuery {
	query := &LeagueCertificateTypeQuery{config: lq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(league.Table, league.FieldID, selector),
			sqlgraph.To(leaguecertificatetype.Table, leaguecertificatetype.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, league.LeagueCertificateTypeTable, league.LeagueCertificateTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first League entity from the query.
// Returns a *NotFoundError when no League was found.
func (lq *LeagueQuery) First(ctx context.Context) (*League, error) {
	nodes, err := lq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{league.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lq *LeagueQuery) FirstX(ctx context.Context) *League {
	node, err := lq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first League ID from the query.
// Returns a *NotFoundError when no League ID was found.
func (lq *LeagueQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = lq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{league.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lq *LeagueQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := lq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single League entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one League entity is found.
// Returns a *NotFoundError when no League entities are found.
func (lq *LeagueQuery) Only(ctx context.Context) (*League, error) {
	nodes, err := lq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{league.Label}
	default:
		return nil, &NotSingularError{league.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lq *LeagueQuery) OnlyX(ctx context.Context) *League {
	node, err := lq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only League ID in the query.
// Returns a *NotSingularError when more than one League ID is found.
// Returns a *NotFoundError when no entities are found.
func (lq *LeagueQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = lq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{league.Label}
	default:
		err = &NotSingularError{league.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lq *LeagueQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := lq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Leagues.
func (lq *LeagueQuery) All(ctx context.Context) ([]*League, error) {
	if err := lq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return lq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (lq *LeagueQuery) AllX(ctx context.Context) []*League {
	nodes, err := lq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of League IDs.
func (lq *LeagueQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := lq.Select(league.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lq *LeagueQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := lq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lq *LeagueQuery) Count(ctx context.Context) (int, error) {
	if err := lq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return lq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (lq *LeagueQuery) CountX(ctx context.Context) int {
	count, err := lq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lq *LeagueQuery) Exist(ctx context.Context) (bool, error) {
	if err := lq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return lq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (lq *LeagueQuery) ExistX(ctx context.Context) bool {
	exist, err := lq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LeagueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lq *LeagueQuery) Clone() *LeagueQuery {
	if lq == nil {
		return nil
	}
	return &LeagueQuery{
		config:                    lq.config,
		limit:                     lq.limit,
		offset:                    lq.offset,
		order:                     append([]OrderFunc{}, lq.order...),
		predicates:                append([]predicate.League{}, lq.predicates...),
		withLeagueCertificateType: lq.withLeagueCertificateType.Clone(),
		// clone intermediate query.
		sql:    lq.sql.Clone(),
		path:   lq.path,
		unique: lq.unique,
	}
}

// WithLeagueCertificateType tells the query-builder to eager-load the nodes that are connected to
// the "league_certificate_type" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LeagueQuery) WithLeagueCertificateType(opts ...func(*LeagueCertificateTypeQuery)) *LeagueQuery {
	query := &LeagueCertificateTypeQuery{config: lq.config}
	for _, opt := range opts {
		opt(query)
	}
	lq.withLeagueCertificateType = query
	return lq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.League.Query().
//		GroupBy(league.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lq *LeagueQuery) GroupBy(field string, fields ...string) *LeagueGroupBy {
	grbuild := &LeagueGroupBy{config: lq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return lq.sqlQuery(ctx), nil
	}
	grbuild.label = league.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.League.Query().
//		Select(league.FieldName).
//		Scan(ctx, &v)
func (lq *LeagueQuery) Select(fields ...string) *LeagueSelect {
	lq.fields = append(lq.fields, fields...)
	selbuild := &LeagueSelect{LeagueQuery: lq}
	selbuild.label = league.Label
	selbuild.flds, selbuild.scan = &lq.fields, selbuild.Scan
	return selbuild
}

func (lq *LeagueQuery) prepareQuery(ctx context.Context) error {
	for _, f := range lq.fields {
		if !league.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lq.path != nil {
		prev, err := lq.path(ctx)
		if err != nil {
			return err
		}
		lq.sql = prev
	}
	return nil
}

func (lq *LeagueQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*League, error) {
	var (
		nodes       = []*League{}
		_spec       = lq.querySpec()
		loadedTypes = [1]bool{
			lq.withLeagueCertificateType != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*League).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &League{config: lq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lq.withLeagueCertificateType; query != nil {
		if err := lq.loadLeagueCertificateType(ctx, query, nodes,
			func(n *League) { n.Edges.LeagueCertificateType = []*LeagueCertificateType{} },
			func(n *League, e *LeagueCertificateType) {
				n.Edges.LeagueCertificateType = append(n.Edges.LeagueCertificateType, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lq *LeagueQuery) loadLeagueCertificateType(ctx context.Context, query *LeagueCertificateTypeQuery, nodes []*League, init func(*League), assign func(*League, *LeagueCertificateType)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*League)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.LeagueCertificateType(func(s *sql.Selector) {
		s.Where(sql.InValues(league.LeagueCertificateTypeColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LeagueID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "league_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lq *LeagueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lq.querySpec()
	_spec.Node.Columns = lq.fields
	if len(lq.fields) > 0 {
		_spec.Unique = lq.unique != nil && *lq.unique
	}
	return sqlgraph.CountNodes(ctx, lq.driver, _spec)
}

func (lq *LeagueQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := lq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (lq *LeagueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   league.Table,
			Columns: league.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: league.FieldID,
			},
		},
		From:   lq.sql,
		Unique: true,
	}
	if unique := lq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, league.FieldID)
		for i := range fields {
			if fields[i] != league.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lq *LeagueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lq.driver.Dialect())
	t1 := builder.Table(league.Table)
	columns := lq.fields
	if len(columns) == 0 {
		columns = league.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lq.sql != nil {
		selector = lq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lq.unique != nil && *lq.unique {
		selector.Distinct()
	}
	for _, p := range lq.predicates {
		p(selector)
	}
	for _, p := range lq.order {
		p(selector)
	}
	if offset := lq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LeagueGroupBy is the group-by builder for League entities.
type LeagueGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lgb *LeagueGroupBy) Aggregate(fns ...AggregateFunc) *LeagueGroupBy {
	lgb.fns = append(lgb.fns, fns...)
	return lgb
}

// Scan applies the group-by query and scans the result into the given value.
func (lgb *LeagueGroupBy) Scan(ctx context.Context, v any) error {
	query, err := lgb.path(ctx)
	if err != nil {
		return err
	}
	lgb.sql = query
	return lgb.sqlScan(ctx, v)
}

func (lgb *LeagueGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range lgb.fields {
		if !league.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lgb *LeagueGroupBy) sqlQuery() *sql.Selector {
	selector := lgb.sql.Select()
	aggregation := make([]string, 0, len(lgb.fns))
	for _, fn := range lgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(lgb.fields)+len(lgb.fns))
		for _, f := range lgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(lgb.fields...)...)
}

// LeagueSelect is the builder for selecting fields of League entities.
type LeagueSelect struct {
	*LeagueQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ls *LeagueSelect) Scan(ctx context.Context, v any) error {
	if err := ls.prepareQuery(ctx); err != nil {
		return err
	}
	ls.sql = ls.LeagueQuery.sqlQuery(ctx)
	return ls.sqlScan(ctx, v)
}

func (ls *LeagueSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := ls.sql.Query()
	if err := ls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
