// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/bug/ent/leaguecertificatetype"
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LeagueCertificateTypeDelete is the builder for deleting a LeagueCertificateType entity.
type LeagueCertificateTypeDelete struct {
	config
	hooks    []Hook
	mutation *LeagueCertificateTypeMutation
}

// Where appends a list predicates to the LeagueCertificateTypeDelete builder.
func (lctd *LeagueCertificateTypeDelete) Where(ps ...predicate.LeagueCertificateType) *LeagueCertificateTypeDelete {
	lctd.mutation.Where(ps...)
	return lctd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lctd *LeagueCertificateTypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lctd.hooks) == 0 {
		affected, err = lctd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LeagueCertificateTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lctd.mutation = mutation
			affected, err = lctd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lctd.hooks) - 1; i >= 0; i-- {
			if lctd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lctd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lctd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lctd *LeagueCertificateTypeDelete) ExecX(ctx context.Context) int {
	n, err := lctd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lctd *LeagueCertificateTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: leaguecertificatetype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: leaguecertificatetype.FieldID,
			},
		},
	}
	if ps := lctd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lctd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// LeagueCertificateTypeDeleteOne is the builder for deleting a single LeagueCertificateType entity.
type LeagueCertificateTypeDeleteOne struct {
	lctd *LeagueCertificateTypeDelete
}

// Exec executes the deletion query.
func (lctdo *LeagueCertificateTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := lctdo.lctd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{leaguecertificatetype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lctdo *LeagueCertificateTypeDeleteOne) ExecX(ctx context.Context) {
	lctdo.lctd.ExecX(ctx)
}
